### ISSUE TITLE
peer requested EAP, config inacceptable

### ISSUE THREAD

**Issue by smalltimecharlie** [jethrocarr/puppet-roadwarrior#1]
Hi Jethro, 

Many thanks for putting this repo together! 

I'm having a few problems getting this to work with an iPhone running 9.3.1. 

I think these lines in the logs are the issue 

Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG] selected peer config 'IPSec-IKEv2'
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] peer requested EAP, config inacceptable
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG] switching to peer config 'IPSec-IKEv2-EAP'

I don't understand why it is trying to do EAP when it should just be using the certificate??!?! 

Any help would be greatly appreciated! 

Thanks 

Charlie 

logs with my road warrior Ip and domain name obsfucated below: 
Client name is simply 'a' 

---

Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] received packet: from {{{roadwarriorIp}}}[3258] to 172.31.1.33[500]
Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] waiting for data on sockets
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[NET] received packet: from {{{roadwarriorIp}}}[3258] to 172.31.1.33[500](604 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N((16430)) ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] looking for an ike config for 172.31.1.33...{{{roadwarriorIp}}}
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   candidate: %any...%any, prio 28
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   candidate: %any...%any, prio 28
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] found matching ike config: %any...%any with prio 28
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[IKE] {{{roadwarriorIp}}} is initiating an IKE_SA
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[IKE] IKE_SA (unnamed)[2] state change: CREATED => CONNECTING
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable DIFFIE_HELLMAN_GROUP found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   no acceptable DIFFIE_HELLMAN_GROUP found
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selecting proposal:
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG]   proposal matches
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] received proposals: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048, IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256, IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_1536, IKE:AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] configured proposals: IKE:AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_2048, IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1536, IKE:3DES_CBC/AES_CBC_128/AES_CBC_192/AES_CBC_256/AES_CTR_128/AES_CTR_192/AES_CTR_256/CAMELLIA_CBC_128/CAMELLIA_CBC_192/CAMELLIA_CBC_256/CAMELLIA_CTR_128/CAMELLIA_CTR_192/CAMELLIA_CTR_256/AES_CCM_8_128/AES_CCM_8_192/AES_CCM_8_256/AES_CCM_12_128/AES_CCM_12_192/AES_CCM_12_256/AES_CCM_16_128/AES_CCM_16_192/AES_CCM_16_256/AES_GCM_8_128/AES_GCM_8_192/AES_GCM_8_256/AES_GCM_12_128/AES_GCM_12_192/AES_GCM_12_256/AES_GCM_16_128/AES_GCM_16_192/AES_GCM_16_256/CAMELLIA_CCM_8_128/CAMELLIA_CCM_8_192/CAMELLIA_CCM_8_256/CAMELLIA_CCM_12_128/CAMELLIA_CCM_12_192/CAMELLIA_CCM_12_256/CAMELLIA_CCM_16_128/CAMELLIA_CCM_16_192/CAMELLIA_CCM_16_256/HMAC_MD5_96/HMAC_SHA1_96/AES_XCBC_96/AES_CMAC_96/HMAC_SHA2_256_128/HMAC_SHA2_384_192/HMAC_SHA2_512_256/PRF_HMAC_MD5/PRF_HMAC_SHA1/PRF_AES128_XCBC/PRF_HMAC_SHA2_256/PRF_HMAC_SHA2_384/PRF_HMAC_SHA2_512/PRF_AES128_CMAC/MODP_1024/MODP_1536/MODP_2048/MODP_3072/MODP_4096/MODP_8192/ECP_256/ECP_384/ECP_521/MODP_1024_160/MODP_2048_224/MODP_2048_256/ECP_192/ECP_224/ECP_224_BP/ECP_256_BP/ECP_384_BP/ECP_512_BP
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[IKE] local host is behind NAT, sending keep alives
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[IKE] remote host is behind NAT
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[IKE] sending cert request for "C=GB, O={{{myVpnName}}}, CN=vpn.{{{myVpnName}}}.com"
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(MULT_AUTH) ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 07[NET] sending packet: from 172.31.1.33[500] to {{{roadwarriorIp}}}[3258](465 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 04[NET] sending packet: from 172.31.1.33[500] to {{{roadwarriorIp}}}[3258]
Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] received packet: from {{{roadwarriorIp}}}[46379] to 172.31.1.33[4500]
Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] waiting for data on sockets
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[NET] received packet: from {{{roadwarriorIp}}}[46379] to 172.31.1.33[4500](528 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) N(MOBIKE_SUP) IDr CPRQ(ADDR DHCP DNS MASK ADDR6 DHCP6 DNS6) N(ESP_TFC_PAD_N) N(NON_FIRST_FRAG) SA TSi TSr ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG] looking for peer configs matching 172.31.1.33[vpn.{{{myVpnName}}}.com]...{{{roadwarriorIp}}}[a@vpn.{{{myVpnName}}}.com]
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG]   candidate "IPSec-IKEv2", match: 20/1/28 (me/other/ike)
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG]   candidate "IPSec-IKEv2-EAP", match: 20/1/28 (me/other/ike)
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG] selected peer config 'IPSec-IKEv2'
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] peer requested EAP, config inacceptable
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[CFG] switching to peer config 'IPSec-IKEv2-EAP'
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] initiating EAP_IDENTITY method (id 0x00)
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP4_ADDRESS attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP4_DHCP attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP4_DNS attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP4_NETMASK attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP6_ADDRESS attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP6_DHCP attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] processing INTERNAL_IP6_DNS attribute
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] received ESP_TFC_PADDING_NOT_SUPPORTED, not using ESPv3 TFC padding
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] peer supports MOBIKE
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] authentication of 'vpn.{{{myVpnName}}}.com' (myself) with RSA signature successful
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[IKE] sending end entity cert "C=GB, O={{{myVpnName}}}, CN=vpn.{{{myVpnName}}}.com"
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[ENC] generating IKE_AUTH response 1 [ IDr CERT AUTH EAP/REQ/ID ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 06[NET] sending packet: from 172.31.1.33[4500] to {{{roadwarriorIp}}}[46379](1504 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 04[NET] sending packet: from 172.31.1.33[4500] to {{{roadwarriorIp}}}[46379]
Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] received packet: from {{{roadwarriorIp}}}[46379] to 172.31.1.33[4500]
Jul 15 00:39:55 ip-172-31-1-33 charon: 03[NET] waiting for data on sockets
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[NET] received packet: from {{{roadwarriorIp}}}[46379] to 172.31.1.33[4500](96 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[ENC] parsed IKE_AUTH request 2 [ EAP/RES/ID ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[IKE] received EAP identity 'a@vpn.{{{myVpnName}}}.com'
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[IKE] loading EAP_TLS method failed
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[ENC] generating IKE_AUTH response 2 [ EAP/FAIL ]
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[NET] sending packet: from 172.31.1.33[4500] to {{{roadwarriorIp}}}[46379](80 bytes)
Jul 15 00:39:55 ip-172-31-1-33 charon: 09[IKE] IKE_SA IPSec-IKEv2-EAP[2] state change: CONNECTING => DESTROYING
Jul 15 00:39:55 ip-172-31-1-33 charon: 04[NET] sending packet: from 172.31.1.33[4500] to {{{roadwarriorIp}}}[46379]

**Comment by jethrocarr** [comment]
hi Charlie,

Just confirming, is this using the .mobileconfig file, or a manual configuration on the iOS device?

regards,
Jethro

**Comment by jethrocarr** [comment]
You are correct in that it should be using "'IPSec-IKEv2" rather than "'IPSec-IKEv2-EAP". It would be handy to see the raw logs and the Puppet DSL you're using because the naming can be very important to get exactly right.

If you're happy to share them with me directly that would be useful - jethro.carr@jethrocarr.com - but if not I'll try my best to assist.

**Comment by smalltimecharlie** [comment]
Hi Jethro, 

I initially tried this with manual configuration (installing the CA and the P12 and then setting up the config in the "add vpn profile" as this is how I'd previously got an IKEv2 vpn on ios 9.1 working previously some months ago). 

I did read about a problem with 9.3 onwards that manually installing the certificates no longer worked so I then used apple configurator to create the profile with the certificates and that got a stage further and it was then connecting to strongswan fine but immediately disconnecting (the iPhone logs look like it has an issue with the certificates on it's end).

I'd have been happy to share logs directly but unfortunately I've actually re purposed the server I was running headless puppet on to run a different strongswan instance (this tutorial using lets encrypt as the CA seems to work okay -  https://dcamero.azurewebsites.net/). However ideally I would like to get a similar setup to yours working so would probably be happy to give it another go as I can't get this setup working in always on mode on a supervised device (even though I can get it working by manually adding the profile which is very frustrating!). 

Have you had any success/tried having your VPN in always on mode on the device? I've hardly seen any success stories for this use case around!

**Comment by jethrocarr** [comment]
This Puppet module generates a complete configuration for you with certs and everything, can you try using that one?

The .mobileconfig file will be found in /etc/ipsec.d/dist/ and is all that's needed for an iOS device. If you can advise whether or not you have issues with this config file or not, it will help considerably with debugging. You can read the file with a text editor incase you have any concerns about it's contents.

My VPN runs in always-on mode other than a config rule that disables it when on my home network (since connecting to a VPN to push the local route isn't wise), works very nicely for me.

**Comment by smalltimecharlie** [comment]
Hi Jethro, 

Thats exciting to know that it works in always on mode on a supervised device! 

I will give it another go today and get back to you with how it went.

**Comment by jethrocarr** [comment]
Actually can't comment on a supervised device - mine is non-supervised.

**Comment by smalltimecharlie** [comment]
Hi Jethro! 

I have it working with a supervised device, many thanks for your help! 

Would you like me to send you slightly changed config? 

Charlie

**Comment by jethrocarr** [comment]
Sure, would be good to see what the difference is.
