### ISSUE TITLE
Change default password

### ISSUE THREAD

**Issue by hylkefaber** [jethrocarr/puppet-roadwarrior#5]
I would like to be able to change the password on the generated configs. Using 'password' as the default password isn't a good idea. Don't get me wrong, this puppet module was key to getting my own setup working, so a great many thanks for making this module, but this security issue bugs me.

**Comment by jethrocarr** [comment]
Send in a PR and I'll be happy to merge it.

**Comment by jethrocarr** [comment]
Actually you can already do this... `roadwarrior::client` takes the param of `cert_password` which you can set to whatever you like.

**Comment by hylkefaber** [comment]
Ah I see, thanks! Could you maybe add this to the wiki or readme?

**Comment by jethrocarr** [comment]
It's already in the readme :-)

`examplephone.p12 - A PCKS/P12 file that includes the client's cert and key capable of being imported to most devices for configuring. If your device can't import, try renaming from .p12 to .pfx and see if that helps. The default password on this file is password.`
